# apps/appsets/guestbook-envs.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-envs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        ns: argocd-dev
      - env: stg
        ns: argocd-stg
      - env: prod
        ns: argocd-prod
  template:
    metadata:
      name: "app-set-{{env}}"
      annotations:
        argocd.argoproj.io/sync-wave: "10"
    spec:
      project: demo
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
          releaseName: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ns}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
