apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-nginx-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: demo
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 18.2.0
    helm:
      values: |
        replicaCount: 3
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
