apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: demo
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      releaseName: guestbook
      values: |
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

